services:
  admin-panel:
    build: .
    container_name: admin-panel
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install --legacy-peer-deps && npm run dev"
